version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:14.17.5
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_PASSWORD: odktest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: node .circleci/initdb.js
      - run: make test-full

