name: OIDC Test

on: push

jobs:
  oidc-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo apt-get install -y curl
    - run: curl -fsSL https://get.docker.com -o get-docker.sh
    - run: sudo sh ./get-docker.sh
    - run: make test-oidc
    - name: Archive playwright screenshots
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Playwright Screenshots
        path: oidc-tester/playwright-tests/results/**/*.png
