name: OIDC e2e tests

on: push

jobs:
  oidc-e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.0
        cache: 'npm'
    - run: sudo apt-get install -y curl
    - run: make test-oidc-e2e
    - name: Fake OIDC Server Logs
      if: always()
      run: docker container ls --all && docker logs --timestamps odk-central-oidc-tester
    - name: Archive playwright screenshots
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Playwright Screenshots
        path: oidc-dev/playwright-results/**/*.png
