name: S3 E2E Tests

on: push

env:
  LOG_LEVEL: DEBUG

jobs:
  s3-e2e:
    timeout-minutes: 15
    # TODO should we use the same container as circle & central?
    runs-on: ubuntu-20.04
    services:
      # see: https://docs.github.com/en/enterprise-server@3.5/actions/using-containerized-services/creating-postgresql-service-containers
      postgres:
        image: postgres:14.10
        env:
          POSTGRES_PASSWORD: odktest
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        # see: https://github.com/minio/minio/discussions/16099
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: odk-central-dev
          MINIO_ROOT_PASSWORD: topSecret123
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -s http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: node lib/bin/create-docker-databases.js
    - name: E2E Test
      timeout-minutes: 10
      run: ./test/e2e/s3/ci
    - name: Backend Logs
      if: always()
      run: "! [[ -f ./backend.log ]] || cat ./backend.log"
